import type { QuestionnaireQuestion } from "./schemas/questionnaire.js";

export const questionnaireDefinition: QuestionnaireQuestion[] = [
  {
    key: "q1_name_and_description",
    title: "Project Summary",
    prompt: "What are you building, and what should it do in plain terms?",
    helpText: "Describe the product in the simplest useful language.",
    order: 1,
    multiline: true,
  },
  {
    key: "q2_who_is_it_for",
    title: "Audience",
    prompt: "Who is it for?",
    helpText: "Name the primary users or customer segments.",
    order: 2,
    multiline: true,
  },
  {
    key: "q3_problem_solved",
    title: "Problem",
    prompt: "What problem does it solve?",
    helpText: "Focus on the pain or gap this product addresses.",
    order: 3,
    multiline: true,
  },
  {
    key: "q4_success_looks_like",
    title: "Success",
    prompt: "What does success look like?",
    helpText: "List the user or business outcomes that would make this successful.",
    order: 4,
    multiline: true,
  },
  {
    key: "q5_out_of_scope",
    title: "Out Of Scope",
    prompt: "What is explicitly out of scope?",
    helpText: "Call out features or markets the project should not cover.",
    order: 5,
    multiline: true,
  },
  {
    key: "q6_main_capabilities",
    title: "Capabilities",
    prompt: "What are the main things it must help people do?",
    helpText: "Describe the core jobs-to-be-done.",
    order: 6,
    multiline: true,
  },
  {
    key: "q7_differentiator",
    title: "Differentiator",
    prompt: "Why would someone choose it over alternatives?",
    helpText: "Mention advantages over current tools or workflows.",
    order: 7,
    multiline: true,
  },
  {
    key: "q8_typical_usage_flow",
    title: "Usage Flow",
    prompt: "How do people typically use it, and for how long?",
    helpText: "Outline the normal usage rhythm, session length, or cadence.",
    order: 8,
    multiline: true,
  },
  {
    key: "q9_platform_and_access",
    title: "Platform",
    prompt: "Where does it run, and how is it accessed?",
    helpText: "Web, mobile, desktop, internal tools, APIs, or other channels.",
    order: 9,
    multiline: true,
  },
  {
    key: "q10_first_user_next_step",
    title: "First-Time Action",
    prompt: "What should a first-time user do first?",
    helpText: "Describe the key first success moment.",
    order: 10,
    multiline: true,
  },
  {
    key: "q11_constraints_and_requirements",
    title: "Constraints",
    prompt: "What constraints, requirements, or realities should shape it?",
    helpText: "Business, legal, operational, timeline, or team constraints.",
    order: 11,
    multiline: true,
  },
  {
    key: "q12_design_references",
    title: "Design References",
    prompt: "What products, references, or visual directions should influence it?",
    helpText: "List inspirations, visual references, or interaction patterns.",
    order: 12,
    multiline: true,
  },
  {
    key: "q13_tech_constraints",
    title: "Technical Constraints",
    prompt: "What technical constraints, integrations, or preferences matter?",
    helpText: "Mention languages, platforms, integrations, hosting, or technical limits.",
    order: 13,
    multiline: true,
  },
  {
    key: "q14_product_feel",
    title: "Product Feel",
    prompt: "How should the product feel in tone and UX?",
    helpText: "Describe the desired user experience and interaction style.",
    order: 14,
    multiline: true,
  },
];
